.PHONY: run consumer generate

run:
	dart run --enable-asserts lib/main.dart
consumer:
	dart run --enable-asserts lib/consumer.dart
generate:
	dart run build_runner build --delete-conflicting-outputs
